[package]
name = "iroha_crypto_core"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ursa = { version = "=0.3.5", default-features = false, features = ["portable"] }
hex = "0.4.0"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
hex-literal = "0.2.1"
serde_json = "1.0"
